import React from 'react'

const Settings = () => {
  return (
    <div>
      <h1>Settings</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias voluptatum est corrupti unde accusantium, quasi doloremque, facere nisi nemo magnam ab ipsa porro hic in esse? Reiciendis facere cum ipsa numquam dolorum accusantium asperiores deserunt perspiciatis. Voluptatem explicabo qui laborum mollitia rem modi sunt delectus in eum quos laudantium a inventore repudiandae illo doloremque odit nostrum officia velit sed, ratione perferendis molestias facilis labore. At suscipit commodi exercitationem illo, cum nulla quo alias quas praesentium repellendus tenetur ipsum? Voluptatum quisquam corrupti perspiciatis accusamus voluptatem, cum sit fugiat, deserunt iure dolorem laboriosam! Obcaecati, dicta perspiciatis, atque nemo suscipit provident dolor deleniti quaerat similique reprehenderit consequuntur voluptate officiis quidem vitae, expedita aliquid. Iste eum fuga ex repellat nesciunt dolores, aliquid, eligendi quam dignissimos cupiditate doloremque, nihil saepe esse magni nulla sed officia possimus quo? Laudantium dicta delectus nisi veritatis eos iure praesentium labore animi, dolore eveniet explicabo incidunt deserunt nam accusamus modi accusantium iste reiciendis, veniam autem! Reiciendis officia, sapiente tempore vero accusantium quod natus perspiciatis sint earum. Aut, nam amet vitae sunt quas dignissimos quisquam expedita quaerat dolore tempore reprehenderit, nihil placeat voluptates deleniti earum reiciendis quasi? Reiciendis, enim, dolore ipsum quae asperiores adipisci non, ullam deleniti praesentium doloribus voluptas cumque exercitationem ratione illum ut est ab autem consectetur saepe debitis qui in. Ex quam qui autem hic explicabo! Fugiat molestias mollitia quaerat ex, praesentium, nihil ab, facilis doloribus quidem nemo labore eius omnis placeat? Porro explicabo, quibusdam harum rerum ut, eos aliquid consequatur magnam vitae placeat libero a? Quas doloremque odio maiores minima commodi incidunt vitae at eos sunt nisi necessitatibus possimus dolore adipisci, saepe corporis recusandae aspernatur, autem distinctio vel beatae perspiciatis. Debitis cum odio sequi beatae, sed quod deleniti itaque quae? Cumque voluptatibus, corrupti facilis distinctio laudantium itaque quibusdam nesciunt, natus recusandae, fuga consequatur aliquid excepturi illum vitae?</p>
    </div>
  )
}

export default Settings
